# auto generated by Alloy Desk
# generated at GENERATE_DATETIME
# generated for task TASK_NAME (TASK_ID)
# used model MODEL_ID
# used dataset DATASET_ID
_base_ = 'BASE_CONFIG'

model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=COUNT_CLASS),
        mask_head=dict(num_classes=COUNT_CLASS)))

# 修改数据集相关设置
dataset_type = 'CocoDataset'
# classes = ('building','bulding_simple','stair','feedlots')
classes = (CLASSES)
# img_prefix='D:/workspace-firok/dataset-22120901/images'
# ann_file='D:/workspace-firok/dataset-22120901/merge-all-coco-remapping-clean.json'
single_dataset = dict(
        img_prefix='IMG_PREFIX',
        classes=classes,
        ann_file='ANNO_FILE')
data = dict(
    # samples_per_gpu=2,
    # workers_per_gpu=2,
    train=single_dataset,
    val=single_dataset,
    test=single_dataset
        )

optimizer = dict(
    type='SGD',
    lr=LR, # 0.0025
    momentum=MOMENTUM, # 0.9
    weight_decay=WEIGHT_DECAY, # 0.0001
      )

runner = dict(type='EpochBasedRunner', max_epochs=MAX_EPOCH) # 108

# load_from = 'D:/workspace-firok/workspace-mmlab/mmdetection/checkpoints/22120901-ep108-ep108.pth'
load_from = 'CHECKPOINT'
