firok:
  spring:
    dbsculptor:
      enable: true
    mvci:
      runtime:
        enable-mapper-config: true
    alloydesk:
      # 储存数据集的目录
      folder-dataset: ./alloy-desk-dataset
      # 储存模型的目录
      folder-model: ./alloy-desk-model
      # 储存任务配置文件之类的目录
      folder-task: ./alloy-desk-task
      # mmdetection 主目录
      # mmdetection 自带的各种脚本都是根据这个路径计算的相对路径
      folder-mmdetection: D:/workspace-firok/workspace-mmlab/mmdetection
      # mmdetection 环境预执行脚本
      mmdetection-pre-script: conda activate open-mmlab
      mmdetection-base-model: D:/workspace-firok/workspace-mmlab/mmdetection/checkpoints/mask_rcnn_r50_caffe_fpn_1x_coco_bbox_mAP-0.38__segm_mAP-0.344_20200504_231812-0ebd1859.pth


server:
  port: 29116
  servlet:
    encoding:
      charset: UTF-8
      force: true
  compression:
    enabled: true
  server-header: Alloy Furnace
#  tomcat:
#    max-http-form-post-size: 200MB
#    max-swallow-size: 200MB

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    path: ./alloy-desk-log/
  logback:
    rollingpolicy:
      clean-history-on-start: true
  level:
    com.lucifer.springboot.cache.mapper: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alloy-desk?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2://~/alloy-desk.db
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariCorePool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select * from information_schema.tables limit 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  #  web:
  #    resources:
  #      static-locations:
  mvc:
    servlet:
      load-on-startup: 100
#    static-path-pattern: /static/**
#    initialization-mode: always
